Accomodate large command results
micromdm/nanomdm pull request #26
Opened 2021-08-05 01:34 UTC by w0de

Hello!

When handling the command result response for InstalledApplicationList, nanomdm issues the following plea:

```
level=info handler=checkin-command msg=command report results err=storing command report: Error 1406: Data too long for column 'result' at row 1
```

The InstalledApplicationList response for my current device - with only base Apple apps - is 117,465 characters of base64-endcoded text. `TEXT` support 65,525 characters; `MEDIUMTEXT`, 16,777,215 (this corresponds to ~16.78 mb: "L + 3 bytes, where L < 2^24" -  https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings)

This works with current nanomdm release (in as much as I migrated with `schema.00005.sql` and everything continued to work/`InstalledApplicationList` started working). MySQL docs do not have any warnings regarding migrating between text types that I found.

2021-08-05 16:52 UTC, jessepeterson commented
Good catch, thanks! We'll also need to have a schema change file to do an ALTER TABLE.

2021-08-05 16:58 UTC, jessepeterson commented
Also: we could go larger with LONGTEXT as well.

2021-08-05 17:25 UTC, w0de commented
> Also: we could go larger with LONGTEXT as well.

I thought about it but proposed MEDIUMTEXT since LONGTEXT can be up to 4GB and `4,294,967,295` - I didn't know if settings someone DB up for that sort of storage requirement was too big an assumption. Will change if you'd prefer LONGTEXT

2021-08-05 17:26 UTC, w0de commented
> Good catch, thanks! We'll also need to have a schema change file to do an ALTER TABLE.

I added schema.00005.sql with the ALTER statement, is that what you mean?

2021-08-07 19:11 UTC, jessepeterson requested changes

2021-08-07 19:11 UTC, jessepeterson commented on storage/mysql/schema.00005.sql
> +ALTER TABLE command_results MODIFY result MEDIUMTEXT;
```suggestion
ALTER TABLE command_results MODIFY result MEDIUMTEXT NOT NULL;
```

2021-08-10 02:49 UTC, jessepeterson approved these changes

2021-08-10 02:51 UTC, merged